variables:
- name: Version
  value: '1.0.0'
- name: Greeting
  value: "G'day, mate"

trigger:
  branches:
    include:
    - master

pr: none

stages:
- stage: BuildWithoutTemplate
  displayName: 'Build without Template'

  jobs:
  - job: HostedVs2017
    displayName: 'Hosted VS2017'
    pool:
      name: 'Hosted VS2017'
    workspace:
      clean: all

    variables:
    - name: Greeting
      value: 'Hello World'

    steps:
    - task: PowerShell@2
      displayName: 'Echo Greeting in PowerShell'
      inputs:
        targetType: Inline
        script: 'Write-Host "$(Greeting)"'

- stage: BuildWithStepsTemplate
  displayName: 'Build with Steps Template'

  jobs:
  - job: HostedVs2017
    displayName: 'Hosted VS2017'
    pool:
      name: 'Hosted VS2017'
    workspace:
      clean: all

    variables:
    - name: Greeting
      value: 'Hello World'

    steps:
    - template: 'template-steps-build.yaml'
      parameters:
        message: 'This is from the steps template'
